import { Zip, ZipDeflate } from "fflate";
import type { ExportBundle } from "@/application/queries/export-bundle.dto";
import { CONSTANTS } from "./constants";

type ZipEntry = { path: string; content: Uint8Array };

/**
 * Serializes an {@link ExportBundle} into a deterministic, streamed ZIP.
 *
 * Streaming (vs `zipSync`) keeps server RAM flat: chunks are deflated
 * and enqueued to the `ReadableStream` as they're produced, so a user
 * with hundreds of versions never materializes the whole archive in
 * memory. Determinism comes from a fixed entry mtime + fixed deflate
 * level, so unchanged data exports byte-for-byte identically.
 *
 * This lives in `infrastructure/` (not the HTTP handler) because ZIP
 * serialization is a transport concern reusable beyond HTTP (e.g. a
 * future CLI export), and `application/` must never import `fflate`.
 */
export class ZipBundleWriter {
  toReadableStream(bundle: ExportBundle): ReadableStream<Uint8Array> {
    const entries = buildEntries(bundle);
    return new ReadableStream<Uint8Array>({
      start(controller) {
        const zip = new Zip((err, chunk, final) => {
          if (err) {
            controller.error(err);
            return;
          }
          controller.enqueue(chunk);
          if (final) controller.close();
        });
        for (const entry of entries) {
          const file = new ZipDeflate(entry.path, {
            level: CONSTANTS.DEFLATE_LEVEL,
          });
          file.mtime = CONSTANTS.ENTRY_MTIME;
          zip.add(file);
          file.push(entry.content, true);
        }
        zip.end();
      },
    });
  }
}

function buildEntries(bundle: ExportBundle): ZipEntry[] {
  const encoder = new TextEncoder();
  const entries: ZipEntry[] = [
    {
      path: CONSTANTS.README_PATH,
      content: encoder.encode(buildReadme(bundle.generatedAt)),
    },
    {
      path: CONSTANTS.INDEX_PATH,
      content: encoder.encode(`${JSON.stringify(bundle, null, 2)}\n`),
    },
  ];

  // `(user_id, slug)` is UNIQUE in the DB, so collisions shouldn't
  // happen — but defend against a corrupt archive if the invariant
  // ever breaks: the second prompt sharing a slug gets an id suffix.
  const usedDirs = new Set<string>();
  for (const prompt of bundle.prompts) {
    let dir = prompt.slug;
    if (usedDirs.has(dir)) dir = `${prompt.slug}-${prompt.id.slice(0, 8)}`;
    usedDirs.add(dir);
    for (const version of prompt.versions) {
      entries.push({
        path: `${CONSTANTS.PROMPTS_DIR}/${dir}/v${version.versionNumber}.md`,
        content: encoder.encode(version.content),
      });
    }
  }

  return entries;
}

function buildReadme(generatedAt: Date): string {
  return `# prompteando export

This archive contains all your prompts and their version history,
exported on ${generatedAt.toISOString()}.

## Structure

- \`index.json\` — machine-readable manifest with metadata for every
  prompt and version.
- \`prompts/<slug>/v<N>.md\` — raw content of each version, by prompt.

## Re-importing

This bundle is portable: any markdown viewer can open the \`v*.md\`
files. The \`index.json\` schema is documented at
https://prompteando.online/docs/export-format (V2).

Generated by prompteando. Your data, always.
`;
}
